MVCWebAssignment1/Models/Event.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MVCWebAssignment1.Models
{
    public class Event
    {
        public int Id { get; set; }
        [Display(Name = "Age Range")]
        public string AgeRange { get; set; }
        [Display(Name = "Gender")]
        public string Gender { get; set; }
        [Display(Name = "Distance")]
        public string Distance { get; set; }
        [Display(Name = "Swimming Stroke")]
        public string SwimmingStroke { get; set; }
        public ICollection<Round> Rounds { get; set; }
        public int MeetId { get; set; }
        public Meet Meet { get; set; }
    }
}

MVCWebAssignment1/Models/EventViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVCWebAssignment1.Models
{
    public class EventViewModel
    {
        public int MeetId { get; set; }
        public Event Event { get; set; }
        public IList<Round> Rounds { get; set; }
    }
}

MVCWebAssignment1/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVCWebAssignment1.Customisations;
using MVCWebAssignment1.DAL;
using MVCWebAssignment1.Models;
using MVCWebAssignment1.ServiceLayer;

namespace MVCWebAssignment1.Controllers
{
    public class EventController : Controller
    {
        private EventService _eventService;

        public EventController()
        {
            _eventService = new EventService();
        }

        public EventController(IEventRepository eventRepository, IMeetRepository meetRepository, IRoundRepository roundRepository)
        {
            this._eventService = new EventService(eventRepository, meetRepository, roundRepository);
        }
        // GET: Event
        [CustomAuthorize(Roles = "Admin")]
        public ActionResult Index()
        {
            return View(_eventService.GetIndex());
        }

        [CustomAuthorize(Roles = "Admin")]
        public ActionResult Details(int id)
        {
            try
            {
                return View(_eventService.GetDetails(id));
            }
            catch(ArgumentException ex)
            {
                return RedirectToAction("Error", "Error", new { errorType = ErrorType.Service, message = ex.Message });
            }
            catch (HttpException ex)
            {
                return RedirectToAction("Error", "Error", new { errorType = ErrorType.Service, message = ex.Message });
            }
        }

        [CustomAuthorize(Roles = "Admin")]
        public ActionResult Create(int MeetId)
        {
            return View(_eventService.CreateView(MeetId));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [CustomAuthorize(Roles = "Admin")]
        public ActionResult Create(EventViewModel eventViewModel)
        {
            ServiceResponse response = _eventService.CreateAction(eventViewModel);

            if(response.Result == true)
            {
                return RedirectToAction("Details", "Meet", new { @id = eventViewModel.MeetId });
            }
            else
            {
                return View(eventViewModel);
            }
        }

        // GET: Event/Edit/5
        [CustomAuthorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            try
            {
                return View(_eventService.EditView(id));
            }
            catch (ArgumentException ex)
            {
                return RedirectToAction("Error", "Error", new { errorType = ErrorType.Service, message = ex.Message });
            }
            catch (HttpException ex)
            {
                return RedirectToAction("Error", "Error", new { errorType = ErrorType.Service, message = ex.Message });
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [CustomAuthorize(Roles = "Admin")]
        public ActionResult Edit(Event @event)
        {
            ServiceResponse response = _eventService.EditAction(@event);

            if(response.Result == true)
            {
                return RedirectToAction("Details", "Event", new { @id = @event.Id });
            }
            else
            {
                return View(@event);
            }
        }

        [CustomAuthorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            try
            {
                return View(_eventService.DeleteView(id));
            }
            catch (ArgumentException ex)
            {
                return RedirectToAction("Error", "Error", new { errorType = ErrorType.Service, message = ex.Message });
            }
            catch (HttpException ex)
            {
                return RedirectToAction("Error", "Error", new { errorType = ErrorType.Service, message = ex.Message });
            }
        }

        [CustomAuthorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ServiceResponse response = _eventService.DeleteAction(id);

            if (response.Result == true)
            {
                return RedirectToAction("Details", "Meet", new { @id = response.ReturnInt });
            }
            else
            {
                return View();
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _eventService.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVCWebAssignment1/Controllers/RoundController.cs
using MVCWebAssignment1.Customisations;
using MVCWebAssignment1.DAL;
using MVCWebAssignment1.Models;
using MVCWebAssignment1.ServiceLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace MVCWebAssignment1.Controllers
{
    public class RoundController : Controller
    {
        private RoundService _roundService;

        public RoundController()
        {
            _roundService = new RoundService();
        }

        public RoundController(IRoundRepository roundRepository, ILaneRepository laneRepository)
        {
            this._roundService = new RoundService(roundRepository, laneRepository);
        }

        [CustomAuthorize(Roles = "Admin")]
        public ActionResult Index()
        {
            return View(_roundService.GetIndex());
        }

        [CustomAuthorize(Roles = "Admin")]
        public ActionResult Create(int EventId)
        {
            ServiceResponse response = _roundService.CreateAction(EventId);

            if (response.Result == true)
            {
                return RedirectToAction("Details", "Event", new { @id = EventId });
            }
            else
            {
                return View();
            }
        }

        [CustomAuthorize(Roles = "Admin")]
        public ActionResult Details(int id)
        {
            try
            {
                return View(_roundService.GetDetails(id));
            }
            catch (ArgumentException ex)
            {
                return RedirectToAction("Error", "Error", new { errorType = ErrorType.Service, message = ex.Message });
            }
            catch (HttpException ex)
            {
                return RedirectToAction("Error", "Error", new { errorType = ErrorType.Service, message = ex.Message });
            }
        }

        [CustomAuthorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            try
            {
                return View(_roundService.DeleteView(id));
            }
            catch (ArgumentException ex)
            {
                return RedirectToAction("Error", "Error", new { errorType = ErrorType.Service, message = ex.Message });
            }
            catch (HttpException ex)
            {
                return RedirectToAction("Error", "Error", new { errorType = ErrorType.Service, message = ex.Message });
            }
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [CustomAuthorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            ServiceResponse response = _roundService.DeleteAction(id);

            if (response.Result == true)
            {
                return RedirectToAction("Details", "Event", new { @id = response.ReturnInt });
            }
            else
            {
                return View();
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _roundService.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVCWebAssignment1/Views/Event/Create.cshtml
@model MVCWebAssignment1.Models.EventViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
@ViewBag.MeetId

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Event</h4>
    <hr />

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.MeetId, new { @Value = Model.MeetId })


    <div class="form-group">
        @Html.LabelFor(model => model.Event.AgeRange, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Event.AgeRange, new[] {
            new SelectListItem() {Text = "Under 14 (Junior)"},
            new SelectListItem() {Text = "Over 16 (Senior)"}
        }, "Choose an option")
        </div>
    </div>

   

    <div class="form-group">
        @Html.LabelFor(model => model.Event.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Event.Gender, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Event.Gender, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Event.Distance, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Event.Distance, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Event.Distance, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Event.SwimmingStroke, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Event.SwimmingStroke, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Event.SwimmingStroke, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Details", "Meet", new { id = Model.MeetId }, null)

</div>

MVCWebAssignment1/Views/Event/Delete.cshtml
@model MVCWebAssignment1.Models.Event

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Event</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AgeRange)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AgeRange)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Distance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Distance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SwimmingStroke)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SwimmingStroke)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MVCWebAssignment1/Views/Event/Details.cshtml
@model MVCWebAssignment1.Models.EventViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Event</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Event.AgeRange)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Event.AgeRange)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Event.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Event.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Event.Distance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Event.Distance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Event.SwimmingStroke)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Event.SwimmingStroke)
        </dd>

    </dl>
</div>
<div>
    <h4>Rounds</h4>
    <hr />
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Rounds[0].RoundNumber)
            </th>
            <th>
                @Html.DisplayName("Number of lanes")
            </th>
            <th>
                @Html.DisplayName("Actions")
            </th>
        </tr>
        @foreach (var item in Model.Rounds)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.RoundNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Lanes.Count)
                </td>
                <td>
                    <button class="btn btn-primary" onclick="location.href='@Url.Action("Details", "Round",new { id = item.Id })';return false;">Round Details</button>
                    <button class="btn btn-danger" onclick="location.href='@Url.Action("Delete","Round",new { id = item.Id })';return false;">Delete</button>
                </td>
            </tr>
        }
    </table>
    <hr/>
    <button class="btn btn-primary glyphicon glyphicon-circle-arrow-left" data-toggle="tooltip" title="Back to Meet" onclick="location.href='@Url.Action("Details", "Meet", new {id = Model.Event.MeetId})';return false;"></button>
    <button class="btn btn-primary glyphicon glyphicon-cog" data-toggle="tooltip" title="Edit Event" onclick="location.href='@Url.Action("Edit","Event", new {id = Model.Event.Id })';return false;"></button>
    <button class="btn btn-success glyphicon glyphicon-plus" data-toggle="tooltip" title="Add new Event" onclick="location.href='@Url.Action("Create", "Round", new {EventId = Model.Event.Id })';return false;"></button>
</div>

MVCWebAssignment1/Views/Event/Edit.cshtml
@model MVCWebAssignment1.Models.Event

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Event</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.AgeRange, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.AgeRange, new[] {
            new SelectListItem() {Text = "Under 14 (Junior)"},
            new SelectListItem() {Text = "Over 16 (Senior)"}
        }, "Choose an option")
        </div>
    </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Distance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Distance, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Distance, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SwimmingStroke, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SwimmingStroke, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SwimmingStroke, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Details", "Meet", new { id = Model.MeetId }, null)
</div>

MVCWebAssignment1/Views/Event/Index.cshtml
@model IEnumerable<MVCWebAssignment1.Models.Event>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.AgeRange)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Distance)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SwimmingStroke)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.AgeRange)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Gender)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Distance)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SwimmingStroke)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>