MVCWebAssignment1/Models/Round.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MVCWebAssignment1.Models
{
    public class Round
    {
        public int Id { get; set; }
        [Display(Name = "Round #")]
        public int RoundNumber { get; set; }
        public ICollection<Lane> Lanes { get; set; }
        //EF6 Reference
        public int EventId { get; set; }
        public Event Event { get; set; }
    }
}

MVCWebAssignment1/Models/RoundViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MVCWebAssignment1.Models
{
    [NotMapped]
    public class RoundViewModel
    {
        public int EventId { get; set; }
        public Round Round { get; set; }
        public ApplicationUser Swimmer { get; set; }
        public IList<Lane> Lanes { get; set; }
        
    }
}

MVCWebAssignment1/Controllers/LaneController.cs
using MVCWebAssignment1.Customisations;
using MVCWebAssignment1.DAL;
using MVCWebAssignment1.Models;
using MVCWebAssignment1.ServiceLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace MVCWebAssignment1.Controllers
{
    public class LaneController : Controller
    {

        private LaneService _laneService { get; set; }

        public LaneController()
        {
            _laneService = new LaneService();
        }

        public LaneController(ILaneRepository laneRepository, ApplicationDbContext _applicationDbContext)
        {
            _laneService = new LaneService(laneRepository, _applicationDbContext);
        }

        [CustomAuthorize(Roles = "Admin")]
        public ActionResult Index()
        {
            return View(_laneService.GetIndex());
        }

        [CustomAuthorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            try
            {
                return View(_laneService.EditView(id));
            }
            catch(ArgumentException ex)
            {
                return RedirectToAction("Error", "Error", new { errorType = ErrorType.Service, message = ex.Message });
            }
            catch (HttpException ex)
            {
                return RedirectToAction("Error", "Error", new { errorType = ErrorType.Service, message = ex.Message });
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [CustomAuthorize(Roles = "Admin")]
        public ActionResult Edit(Lane lane)
        {
            ServiceResponse response = _laneService.EditAction(lane);

            if (response.Result == true)
            {
                return RedirectToAction("Details", "Round", new { @id = lane.RoundId});
            }
            else
            {
                return View(response.ServiceObject as Lane);
            }
        }

        [CustomAuthorize(Roles = "Admin")]
        public ActionResult Create(int RoundId)
        {
            return View(_laneService.CreateView(RoundId));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [CustomAuthorize(Roles = "Admin")]
        public ActionResult Create(LaneViewModel laneViewModel)
        {
            ServiceResponse response = _laneService.CreateAction(laneViewModel);

            if(response.Result == true)
            {
                return RedirectToAction("Details", "Round", new { @id = laneViewModel.RoundId });

            }
            else
            {
                return View(laneViewModel);
            }
        }

        [CustomAuthorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            try
            {
                return View(_laneService.DeleteView(id));
            }
            catch (ArgumentException ex)
            {
                return RedirectToAction("Error", "Error", new { errorType = ErrorType.Service, message = ex.Message });
            }
            catch (HttpException ex)
            {
                return RedirectToAction("Error", "Error", new { errorType = ErrorType.Service, message = ex.Message });
            }
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [CustomAuthorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            ServiceResponse response = _laneService.DeleteAction(id);

            if (response.Result == true)
            {
                return RedirectToAction("Details", "Round", new { @id = response.ReturnInt});
            }
            else
            {
                return View();
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _laneService.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVCWebAssignment1/Controllers/RoundController.cs
using MVCWebAssignment1.Customisations;
using MVCWebAssignment1.DAL;
using MVCWebAssignment1.Models;
using MVCWebAssignment1.ServiceLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace MVCWebAssignment1.Controllers
{
    public class RoundController : Controller
    {
        private RoundService _roundService;

        public RoundController()
        {
            _roundService = new RoundService();
        }

        public RoundController(IRoundRepository roundRepository, ILaneRepository laneRepository)
        {
            this._roundService = new RoundService(roundRepository, laneRepository);
        }

        [CustomAuthorize(Roles = "Admin")]
        public ActionResult Index()
        {
            return View(_roundService.GetIndex());
        }

        [CustomAuthorize(Roles = "Admin")]
        public ActionResult Create(int EventId)
        {
            ServiceResponse response = _roundService.CreateAction(EventId);

            if (response.Result == true)
            {
                return RedirectToAction("Details", "Event", new { @id = EventId });
            }
            else
            {
                return View();
            }
        }

        [CustomAuthorize(Roles = "Admin")]
        public ActionResult Details(int id)
        {
            try
            {
                return View(_roundService.GetDetails(id));
            }
            catch (ArgumentException ex)
            {
                return RedirectToAction("Error", "Error", new { errorType = ErrorType.Service, message = ex.Message });
            }
            catch (HttpException ex)
            {
                return RedirectToAction("Error", "Error", new { errorType = ErrorType.Service, message = ex.Message });
            }
        }

        [CustomAuthorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            try
            {
                return View(_roundService.DeleteView(id));
            }
            catch (ArgumentException ex)
            {
                return RedirectToAction("Error", "Error", new { errorType = ErrorType.Service, message = ex.Message });
            }
            catch (HttpException ex)
            {
                return RedirectToAction("Error", "Error", new { errorType = ErrorType.Service, message = ex.Message });
            }
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [CustomAuthorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            ServiceResponse response = _roundService.DeleteAction(id);

            if (response.Result == true)
            {
                return RedirectToAction("Details", "Event", new { @id = response.ReturnInt });
            }
            else
            {
                return View();
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _roundService.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVCWebAssignment1/Views/Round/Delete.cshtml
@model MVCWebAssignment1.Models.Round

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Round</h4>
    <hr />
    <dl class="dl-horizontal">
        <h3>Deleting this round will delete all attributed lanes and reorder existing rounds.</h3>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MVCWebAssignment1/Views/Round/Details.cshtml
@model MVCWebAssignment1.Models.RoundViewModel

@{
    ViewBag.Title = "Round " + Model.Round.RoundNumber;
}

<h2>Round @Model.Round.RoundNumber</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Lanes[0].LaneNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Lanes[0].Swimmer.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Lanes[0].FinishTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Lanes[0].LaneComment)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model.Lanes)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.LaneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Swimmer.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FinishTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LaneComment)
            </td>
            <td>
                <button class="btn btn-primary" onclick="location.href='@Url.Action("Edit","Lane", new { id = item.Id })';return false;">Record Time</button>
                <button class="btn btn-danger" onclick="location.href='@Url.Action("Delete","Lane",new { id = item.Id })';return false;">Delete Lane</button>
            </td>
        </tr>
    }
</table>
<hr />
<button class="btn btn-primary glyphicon glyphicon-circle-arrow-left" data-toggle="tooltip" title="Back to Event" onclick="location.href='@Url.Action("Details", "Event", new { id = Model.Round.EventId })';return false;"></button>
<button class="btn btn-success glyphicon glyphicon-plus" data-toggle="tooltip" title="Add new Event" onclick="location.href='@Url.Action("Create", "Lane", new {RoundId = Model.Round.Id })';return false;"></button>